### ISSUE TITLE
IOError: [Errno 21] Is a directory: '/tmp/app.tar.gz'

### ISSUE THREAD

**Issue by roblee357** [DINGDAMU/Network-wide-heavy-hitter-detection#1]
Hello. I'm getting this error at step 5.

v2-local@v2local-VirtualBox:~/Desktop/Network-wide-heavy-hitter-detection$ sudo ./p4app run nwhhd.p4app 
Entering build directory.
Extracting package.
Traceback (most recent call last):
  File "./p4apprunner.py", line 323, in <module>
    main()
  File "./p4apprunner.py", line 286, in main
    tar = tarfile.open(args.app)
  File "/usr/lib/python2.7/tarfile.py", line 1673, in open
    return func(name, "r", fileobj, **kwargs)
  File "/usr/lib/python2.7/tarfile.py", line 1738, in gzopen
    fileobj = gzip.GzipFile(name, mode, compresslevel, fileobj)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 21] Is a directory: '/tmp/app.tar.gz'

**Comment by DINGDAMU** [comment]
Hi,

I tried my program on my server, it works well.

It seems that you are running the program on a virtual machine. 
Maybe some dependencies are missing in your environment.

An official repository is [here](https://github.com/p4lang/p4app).
Hope it helps.

**Comment by roblee357** [comment]
Thank you sir. I reran in the P4lang tutorials vm setup by Vagrant and VirtualBox and it works.
